### ISSUE TITLE
How to use this API

### ISSUE THREAD

**Issue by abdelouali** [BekoDesign/versio-php-api#6]
Hi,

I would like to use this API. I did like you told but still have no result:

Below you find my code:

```
<?php

require 'versioAPI/Client.php';


$username = "eamil";
$password = "passwd";

$client = new Client(
    $username,
    $password
);


$client->categories()->list();
}
```

What do i do wrong?

Thanks

**Comment by beko1997** [comment]
Could you please share the error message which is returned when your code is executed? 

Their is also an extra `}` at the end of your code, but I guess that is just a copy mistake?

**Comment by abdelouali** [comment]
Hi,

i just get the HTTP ERROR 500 message.

Thank you

**Comment by beko1997** [comment]
Well that is not much to work with. Is there some system log or could you try to turn on error reporting? 
```php
// Turn off all error reporting
error_reporting(0);
```
http://php.net/manual/en/function.error-reporting.php

What I expect is that since you are not using composers autoload file that there are some classes that can not be found. You could try to import more classes. Simply require the contracts, models en traits that you require. In this case for the category. Although I would really recommend to use the Composer package. 

Please also check your PHP version since this script is made for PHP 7.1+ and will not work on older versions.

**Comment by beko1997** [comment]
Please feel free to reply to this issue. I will close this issue for now because there is no answer for over a week.

**Comment by abdelouali** [comment]
Hi, sorry for the late reply. 

I have added the code you suggested but I still got no response

`$curl = curl_init();
curl_setopt($curl, CURLOPT_URL,'https://www.versio.nl/api/v1/contacts');
curl_setopt($curl, CURLOPT_USERPWD, $versioLogin);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET"); 
curl_setopt($ch, CURLOPT_HTTPHEADER, array( 'Content-Type: application/json', 'Content-Length: '. strlen($data_string))); 
$response = curl_exec($curl);

echo $response;`

**Comment by beko1997** [comment]
As far I can workout Guzzle 6 HTTP client does not require and depend on CURL. Did you add the IP address from the machine where the script is running from to the Versio console? https://www.versio.nl/customer/account/api

And did you find the PHP error log? Because there will be important information there.

**Comment by abdelouali** [comment]
What IP do i need to add? The server's or my personal IP?

**Comment by beko1997** [comment]
The outgoing IP address of the machine that executes the code. Versio will deny any access to the API when the IP address is not known.
